### ISSUE TITLE
Vercel build runs regardless of Github actions

### ISSUE THREAD

**Issue by bradymwilliams** [8bittitan/screamo-stack#6]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

Make small intentional type errors, see that vercel deployments still execute

Wondering if you can point me in a direction to extend your CI.yml. I see you've made some work on the CI front here but vercel doesn't seem to care about it. 

### Expected Behavior

Vercel doesn't deploy

### Actual Behavior

Vercel deploys with errors

**Comment by 8bittitan** [comment]
Hi @bradymwilliams, thanks for checking out this stack!

To solve this, you could set Vercel to not build from GitHub source and instead build the app in the action and then deploy to Vercel from there. That way you can prevent the deploy if any of the steps fail for some reason.

Vercel has a nice article written about it here: https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

Let me know if you have anymore questions!
